name: Deploy docs

on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk update
          apk add rsync 
      - name: Build Docs
        run: |
          asciidoctor docs/index.adoc
          find . -name .adoc -exec rm -rf '{}' \;
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/main')
        with:
          branch: gh-pages
          folder: docs
          clean: true
